import {NextRequest,NextResponse} from "next/server";import crypto from "crypto";import {sbFetch} from "../../../../lib/server-supabase";
const bands=["0-5","6-10","11-15","16-20","20+"] as const;
const species=["Lion","Leopard","Cheetah","African wild dog","Spotted hyena","Elephant","Black rhino","White rhino","Buffalo","Giraffe","Hippo","Wildebeest","Zebra","Pangolin","Aardvark","Honey badger","Serval","Caracal","Gorilla","Chimpanzee","Shoebill"] as const;
const events=["None","Active hunt","Kill / feeding","With young","Migration / crossing","Unusually large herd"] as const;
const sensitive=new Set(["Black rhino","White rhino","Pangolin"]);
async function guide(req:NextRequest){const t=req.cookies.get("fr_guide_session")?.value;if(!t)return null;const h=crypto.createHash("sha256").update(t).digest("hex"),r=await sbFetch("safari_guides?session_token_hash=eq."+h+"&session_expires_at=gt."+encodeURIComponent(new Date().toISOString())+"&role=eq.guide&select=id,display_name,parent_operator_id,status&limit=1");return(await r.json())[0]}
function km(a:number,b:number,c:number,d:number){const R=6371,x=(c-a)*Math.PI/180,y=(d-b)*Math.PI/180,q=Math.sin(x/2)**2+Math.cos(a*Math.PI/180)*Math.cos(c*Math.PI/180)*Math.sin(y/2)**2;return 2*R*Math.asin(Math.sqrt(q))}
async function nearby(lat:number,lng:number,park:string|null){const since=new Date(Date.now()-5*60*1000).toISOString();const q="safari_vehicle_presence?updated_at=gte."+encodeURIComponent(since)+(park?"&park_code=eq."+encodeURIComponent(park):"")+"&select=latitude,longitude";const r=await sbFetch(q);if(!r.ok)return 0;const rows=await r.json();return rows.filter((x:any)=>km(lat,lng,x.latitude,x.longitude)<=0.25).length}
export async function POST(req:NextRequest){try{const g=await guide(req);if(!g||g.status==="suspended")return NextResponse.json({error:"Authenticated guide required."},{status:401});const b=await req.json().catch(()=>null);if(!b||!species.includes(b.species)||!bands.includes(b.vehicleBand)||typeof b.lat!=="number"||typeof b.lng!=="number")return NextResponse.json({error:"Invalid sighting"},{status:400});const ev=events.includes(b.event)?b.event:"None",park=b.parkCode?String(b.parkCode).slice(0,40):null;const row={id:"SI-"+crypto.randomUUID().slice(0,8).toUpperCase(),species:b.species,latitude:b.lat,longitude:b.lng,vehicle_band:b.vehicleBand,sighting_event:ev==="None"?null:ev,sensitive_location:sensitive.has(b.species),guide_name:g.display_name,guide_id:g.id,park_code:park,status:"active",confirmations:1,reported_at:new Date().toISOString(),updated_at:new Date().toISOString()};const r=await sbFetch("safari_sightings",{method:"POST",headers:{Prefer:"return=representation"},body:JSON.stringify(row)});if(!r.ok)return NextResponse.json({error:"Could not save sighting"},{status:502});const saved=(await r.json())[0];return NextResponse.json({...saved,platform_vehicles_nearby:await nearby(b.lat,b.lng,park)},{status:201})}catch{return NextResponse.json({error:"Safari persistence is not configured."},{status:503})}}
export async function GET(req:NextRequest){try{const g=await guide(req);if(!g||g.status==="suspended")return NextResponse.json({error:"Authenticated guide required."},{status:401});const r=await sbFetch("safari_sightings?status=eq.active&order=updated_at.desc&limit=50");if(!r.ok)return NextResponse.json({error:"Could not load sightings"},{status:502});const rows=await r.json();return NextResponse.json(await Promise.all(rows.map(async(x:any)=>({...x,platform_vehicles_nearby:await nearby(x.latitude,x.longitude,x.park_code)}))))}catch{return NextResponse.json({error:"Safari persistence is not configured."},{status:503})}}