"use client";
import {useMemo,useState} from "react";
import {ArrowRight,BadgeCheck,CalendarDays,CarFront,ChevronDown,CircleDollarSign,Headphones,MapPin,Menu,Plane,ShieldCheck,UsersRound,X} from "lucide-react";
const routes=[{name:"Stone Town",price:15,time:"15–20 min",image:"https://images.unsplash.com/photo-1580746738099-67e2a71e8913?auto=format&fit=crop&w=1000&q=85"},{name:"Nungwi",price:40,time:"60–70 min",image:"https://images.unsplash.com/photo-1573843981267-be1999ff37cd?auto=format&fit=crop&w=1000&q=85"},{name:"Paje",price:40,time:"60–70 min",image:"https://images.unsplash.com/photo-1510414842594-a61c69b5ae57?auto=format&fit=crop&w=1000&q=85"}];
export default function Home(){const[destination,setDestination]=useState("");const[trip,setTrip]=useState<"oneway"|"return">("oneway");const[menu,setMenu]=useState(false);const selected=useMemo(()=>routes.find(r=>r.name===destination),[destination]);function choose(name:string){setDestination(name);document.getElementById("book")?.scrollIntoView({behavior:"smooth"})}return <main>
<section className="hero"><nav className="nav shell"><a className="brand" href="#">Fixed<span>Rider</span></a><div className={"navlinks "+(menu?"open":"")}><a href="#routes">Zanzibar <ChevronDown size={14}/></a><a href="#how">How it works</a><a href="#routes">Popular routes</a><a href="#drivers">For drivers</a></div><div className="navright"><span>USD</span><a href="#help">Help</a><a className="pill gold" href="#book">Book a ride <ArrowRight size={16}/></a></div><button className="menubtn" aria-label="Menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav><div className="heroShade"/>
<div className="shell heroContent"><div className="heroCopy"><div className="eyebrow">ZANZIBAR AIRPORT TRANSFERS</div><h1>One route.<br/>One clear price.</h1><p>Reliable, comfortable transfers across Zanzibar.<br/>Know your fare before you go.</p><div className="trustRow"><div><CircleDollarSign/><b>Fixed prices</b><span>No negotiation</span></div><div><ShieldCheck/><b>Verified drivers</b><span>Clear driver details</span></div><div><CarFront/><b>Modern vehicles</b><span>Comfortable travel</span></div></div></div>
<div id="book" className="booking"><div className="bookingTop"><div className="tabs"><button className={trip==="oneway"?"active":""} onClick={()=>setTrip("oneway")}>One-way</button><button className={trip==="return"?"active":""} onClick={()=>setTrip("return")}>Return</button></div><span><UsersRound size={17}/> No account needed</span></div><div className="fields"><div className="field"><Plane/><label>From<strong>Zanzibar Airport (ZNZ)</strong></label><ChevronDown/></div><div className="field"><MapPin/><label>To<select value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Select destination</option>{routes.map(r=><option key={r.name}>{r.name}</option>)}</select></label><ChevronDown/></div><a className="showPrice" href={selected?"#quote":"#routes"}>{selected?("$"+selected.price+" · Continue"):"Show prices"} <ArrowRight size={18}/></a></div>
{selected&&<div id="quote" className="quote"><BadgeCheck/><span><small>{trip==="return"?"Estimated return total":"Launch reference fare"}</small><strong>{trip==="return"?("$"+selected.price*2):("$"+selected.price)} to {selected.name}</strong></span><button>Request this ride <ArrowRight size={16}/></button></div>}<div id="how" className="benefits"><div><CircleDollarSign/><span><b>Instant price</b><small>See your fare in seconds</small></span></div><div><CalendarDays/><span><b>Flexible booking</b><small>Change plans easily</small></span></div><div><Headphones/><span><b>Local support</b><small>We're here to help</small></span></div></div></div></div></section>
<section id="routes" className="routes shell"><div className="sectionHead"><div><div className="eyebrow sand">POPULAR ROUTES</div><h2>Most booked in Zanzibar</h2></div><a href="#book">View all routes <ArrowRight size={16}/></a></div><div className="routeGrid"><div className="cards">{routes.map(r=><article className="routeCard" key={r.name}><img src={r.image} alt={r.name}/><div className="routeBody"><div className="routeLine"><span><Plane size={15}/> Zanzibar Airport (ZNZ)<br/><b>↓ &nbsp; {r.name}</b></span><strong>${r.price}<small>per vehicle</small></strong></div><div className="time"><CarFront size={15}/> ~ {r.time}</div><button onClick={()=>choose(r.name)}>Book now <ArrowRight size={15}/></button></div></article>)}</div>
<aside id="drivers" className="driverCard"><div className="driverOverlay"/><div className="driverContent"><div className="eyebrow">FOR DRIVERS</div><h2>Keep <span>100%</span><br/>of your fare.</h2><ul><li>✓ $0 to join</li><li>✓ First 3 months free</li><li>✓ $10–15 one-time activation from month 4</li><li>✓ Simple monthly membership thereafter</li><li>✓ 0% commission on trips</li></ul><a className="pill gold" href="mailto:drivers@fixedrider.com?subject=FixedRider%20Zanzibar%20driver%20interest">Join as a driver <ArrowRight size={16}/></a><div className="driverFoot"><UsersRound/><span><b>Be part of a driver-first network.</b><small>Fair prices. More bookings. Local support.</small></span></div></div></aside></div><p className="priceNote">Launch fares shown are reference prices for validation and may change before confirmed booking.</p></section>
<footer id="help"><div className="shell footer"><a className="brand dark" href="#">Fixed<span>Rider</span></a><p>Zanzibar-first. Clear fares. Verified local drivers.</p><div><a href="#book">Book</a><a href="#drivers">Drive</a><a href="mailto:hello@fixedrider.com">Contact</a></div></div></footer></main>}