"use client";
import {useMemo,useState} from "react";
import {ArrowRight,BadgeCheck,Binoculars,ChevronDown,Clock3,MapPin,Menu,Plane,ShieldCheck,UsersRound,X} from "lucide-react";
const sightings=[{animal:"Leopard",age:"11 min ago",distance:"4.2 km",confirmations:3,slots:"6 / 10",status:"Viewing open"},{animal:"Lion",age:"18 min ago",distance:"7.8 km",confirmations:5,slots:"2 / 8",status:"Limited access"},{animal:"Elephant herd",age:"7 min ago",distance:"3.1 km",confirmations:4,slots:"12 / 15",status:"Viewing open"}];
const routes=[{name:"Stone Town",price:15},{name:"Nungwi",price:40},{name:"Paje",price:40}];
export default function Home(){const[destination,setDestination]=useState("");const[menu,setMenu]=useState(false);const selected=useMemo(()=>routes.find(r=>r.name===destination),[destination]);return <main>
<section className="safariHero"><nav className="nav shell"><a className="brand" href="#">Fixed<span>Rider</span></a><div className={"navlinks "+(menu?"open":"")}><a href="#safari">Safari Intelligence</a><a href="#guides">For guides</a><a href="#transfers">Transfers</a><a href="#how">How it works</a></div><div className="navright"><a className="pill gold" href="#pilot">Join the pilot <ArrowRight size={16}/></a></div><button className="menubtn" aria-label="Menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></nav><div className="heroShade"/>
<div className="shell safariHeroContent"><div className="heroCopy"><div className="eyebrow">SAFARI INTELLIGENCE</div><h1>Stop driving blind.</h1><p>Live wildlife intelligence for safari guides. Share verified sightings, reduce wasted searching and manage viewing pressure before vehicles converge.</p><div className="heroActions"><a className="pill gold" href="#pilot">Activate pilot pass <ArrowRight size={16}/></a><a className="textLink" href="#guides">I’m a guide <ArrowRight size={16}/></a></div><div className="trustRow"><div><BadgeCheck/><b>Guide-confirmed</b><span>Sightings gain confidence</span></div><div><MapPin/><b>Location-aware</b><span>Fresh GPS + time</span></div><div><UsersRound/><b>Controlled access</b><span>Viewing slots, not crowds</span></div></div></div>
<div id="safari" className="intelPanel"><div className="intelTop"><span><i className="liveDot"/> PILOT VIEW</span><small>Illustrative interface</small></div><h3>Live nearby sightings</h3><div className="sightingList">{sightings.map(s=><article key={s.animal} className="sighting"><div className="animalIcon"><Binoculars/></div><div className="sightingMain"><b>{s.animal}</b><span><Clock3 size={13}/>{s.age} · {s.distance}</span><small>Confirmed by {s.confirmations} guides</small></div><div className="slots"><small>{s.status}</small><strong>{s.slots}</strong><span>slots</span></div></article>)}</div><div className="intelFoot"><ShieldCheck/><span><b>Sensitive sightings can be restricted.</b><small>Park rules and conservation controls remain part of the operating model.</small></span></div></div></div></section>
<section id="how" className="how shell"><div className="sectionHead"><div><div className="eyebrow sand">ONE NETWORK</div><h2>Guides create the intelligence.</h2></div><p>The tourist pays once. The guide stays the interface. FixedRider handles attribution and the live network.</p></div><div className="steps"><article><span>01</span><Binoculars/><h3>Spot</h3><p>A participating guide reports an animal. GPS and time are captured with the report.</p></article><article><span>02</span><BadgeCheck/><h3>Confirm</h3><p>Independent guide confirmations improve confidence and stale reports lose value.</p></article><article><span>03</span><UsersRound/><h3>Control</h3><p>Viewing availability can limit how many vehicles are directed toward a sighting.</p></article></div></section>
<section id="guides" className="guideSection"><div className="shell guideGrid"><div><div className="eyebrow">FOR SAFARI GUIDES</div><h2>Share better sightings.<br/>Earn from participation.</h2><p>Guides are the network, not an afterthought. A guide can introduce a visitor to the Safari Intelligence Pass and receive an attributed share without collecting cash from the guest.</p><div className="economics"><div><small>Safari Intelligence Pass</small><strong>$5</strong><span>pilot concept / tourist / day</span></div><div><small>Guide share</small><strong>$1.50</strong><span>proposed pilot attribution</span></div></div><p className="micro">Pilot economics are proposed for validation and are not yet a park tariff or guaranteed guide payment.</p></div><div id="pilot" className="pilotCard"><div className="eyebrow sand">GUIDE PILOT</div><h3>Start with the people already in the vehicle.</h3><ul><li>Guide-specific QR / referral attribution</li><li>Tourist pays FixedRider directly</li><li>No guide cash reconciliation</li><li>Verified contributions can feed a contributor pool</li><li>Park-compatible controls from day one</li></ul><button type="button">Pilot registration coming next <ArrowRight size={16}/></button></div></div></section>
<section id="transfers" className="transferSection shell"><div className="sectionHead"><div><div className="eyebrow sand">FIXEDRIDER TRANSFERS</div><h2>And before the safari: one clear transfer price.</h2></div><p>Zanzibar remains the first transfer market, but transport is now the second product line.</p></div><div className="transferBox"><div className="transferIntro"><Plane/><div><b>Zanzibar Airport (ZNZ)</b><span>Choose a common destination to see the current launch reference fare.</span></div></div><div className="transferSelect"><MapPin/><select value={destination} onChange={e=>setDestination(e.target.value)}><option value="">Select destination</option>{routes.map(r=><option key={r.name}>{r.name}</option>)}</select><ChevronDown/></div><div className="transferPrice">{selected?<><small>Launch reference fare</small><strong>${selected.price}</strong><span>per vehicle · validation price</span></>:<><small>Fixed-price transfer</small><strong>—</strong><span>No negotiation at pickup</span></>}</div></div></section>
<footer><div className="shell footer"><a className="brand dark" href="#">Fixed<span>Rider</span></a><p>Safari intelligence first. Fixed-price transfers second.</p><div><a href="#safari">Safari</a><a href="#guides">Guides</a><a href="#transfers">Transfers</a></div></div></footer></main>}