export const locales=["en","it","de","fr","pl","ru","es"] as const;export type Locale=typeof locales[number];export const copy={en:{transfer:"Zanzibar private transfer",fare:"Fixed fare",book:"Check this transfer",both:"One route pair. One fare in either direction."},it:{transfer:"Transfer privato a Zanzibar",fare:"Tariffa fissa",book:"Controlla questo transfer",both:"Una tratta. Una tariffa in entrambe le direzioni."},de:{transfer:"Privater Transfer auf Sansibar",fare:"Festpreis",book:"Transfer prüfen",both:"Eine Strecke. Ein Preis in beide Richtungen."},fr:{transfer:"Transfert privé à Zanzibar",fare:"Tarif fixe",book:"Vérifier ce transfert",both:"Un trajet. Un tarif dans les deux sens."},pl:{transfer:"Prywatny transfer na Zanzibarze",fare:"Stała cena",book:"Sprawdź transfer",both:"Jedna trasa. Jedna cena w obu kierunkach."},ru:{transfer:"Частный трансфер на Занзибаре",fare:"Фиксированная цена",book:"Проверить трансфер",both:"Один маршрут. Одна цена в обоих направлениях."},es:{transfer:"Traslado privado en Zanzíbar",fare:"Tarifa fija",book:"Consultar este traslado",both:"Una ruta. Un precio en ambas direcciones."}} as const;
export const tanzaniaCopy={
en:{transfer:"Tanzania private transfer",book:"Check this transfer",both:"One route pair. One price in either direction.",intro:"Private transfers between airports, safari gateways, cities and lodges across mainland Tanzania."},
it:{transfer:"Transfer privato in Tanzania",book:"Verifica questo transfer",both:"Una tratta, un unico prezzo in entrambe le direzioni.",intro:"Transfer privati tra aeroporti, località safari, città e lodge nella Tanzania continentale."},
de:{transfer:"Privater Transfer in Tansania",book:"Transfer prüfen",both:"Eine Strecke, ein Preis in beide Richtungen.",intro:"Private Transfers zwischen Flughäfen, Safari-Ausgangspunkten, Städten und Lodges auf dem tansanischen Festland."},
fr:{transfer:"Transfert privé en Tanzanie",book:"Vérifier ce transfert",both:"Un trajet, un même tarif dans les deux sens.",intro:"Transferts privés entre aéroports, points de départ de safari, villes et lodges en Tanzanie continentale."},
pl:{transfer:"Prywatny transfer w Tanzanii",book:"Sprawdź transfer",both:"Jedna trasa, jedna cena w obu kierunkach.",intro:"Prywatne transfery między lotniskami, bazami safari, miastami i lodge'ami w kontynentalnej Tanzanii."},
ru:{transfer:"Частный трансфер по Танзании",book:"Проверить трансфер",both:"Один маршрут — одна цена в обоих направлениях.",intro:"Частные трансферы между аэропортами, сафари-локациями, городами и лоджами материковой Танзании."},
es:{transfer:"Traslado privado en Tanzania",book:"Consultar este traslado",both:"Una ruta, un precio en ambas direcciones.",intro:"Traslados privados entre aeropuertos, puntos de safari, ciudades y alojamientos en Tanzania continental."}
} as const;
export const rideCopy={en:{ride:"Private ride",book:"Check this ride",intro:"Private rides between airports, hotels, cities and tourism destinations."},it:{ride:"Transfer privato",book:"Controlla questa corsa",intro:"Transfer privati tra aeroporti, hotel, città e destinazioni turistiche."},de:{ride:"Privater Transfer",book:"Transfer prüfen",intro:"Private Transfers zwischen Flughäfen, Hotels, Städten und Reisezielen."},fr:{ride:"Transfert privé",book:"Vérifier ce trajet",intro:"Transferts privés entre aéroports, hôtels, villes et destinations touristiques."},pl:{ride:"Prywatny transfer",book:"Sprawdź przejazd",intro:"Prywatne transfery między lotniskami, hotelami, miastami i miejscami turystycznymi."},ru:{ride:"Частный трансфер",book:"Проверить поездку",intro:"Частные трансферы между аэропортами, отелями, городами и туристическими направлениями."},es:{ride:"Traslado privado",book:"Consultar este traslado",intro:"Traslados privados entre aeropuertos, hoteles, ciudades y destinos turísticos."}} as const;
