export type KenyaZone={slug:string;name:string;region:"nairobi"|"coast"|"south"|"rift"|"central"|"north"|"west";aliases:string[]};
export const kenyaZones:KenyaZone[]=[
["jkia","Jomo Kenyatta International Airport (NBO)","nairobi",["jkia","nbo","jomo kenyatta international airport","nairobi airport"]],["nairobi-cbd","Nairobi CBD","nairobi",["nairobi cbd","nairobi city centre","nairobi city center"]],["westlands","Westlands","nairobi",["westlands"]],["karen","Karen","nairobi",["karen"]],["gigiri","Gigiri","nairobi",["gigiri"]],["upper-hill","Upper Hill","nairobi",["upper hill"]],["wilson","Wilson Airport (WIL)","nairobi",["wilson airport","wil"]],["nairobi-national-park","Nairobi National Park","nairobi",["nairobi national park"]],
["namanga","Namanga Border","south",["namanga","namanga border"]],["amboseli","Amboseli National Park","south",["amboseli","amboseli national park"]],["emali","Emali","south",["emali"]],["voi","Voi","south",["voi"]],["tsavo-east","Tsavo East National Park","south",["tsavo east"]],["tsavo-west","Tsavo West National Park","south",["tsavo west"]],["taita-hills","Taita Hills / Lumo","south",["taita hills","lumo","lions bluff"]],
["mombasa-airport","Moi International Airport (MBA)","coast",["mba","moi international airport","mombasa airport"]],["mombasa","Mombasa","coast",["mombasa"]],["nyali","Nyali","coast",["nyali"]],["bamburi","Bamburi","coast",["bamburi"]],["diani","Diani Beach","coast",["diani","diani beach"]],["ukunda","Ukunda Airport (UKA)","coast",["ukunda airport","uka"]],["kilifi","Kilifi","coast",["kilifi"]],["watamu","Watamu","coast",["watamu"]],["malindi","Malindi","coast",["malindi"]],["malindi-airport","Malindi Airport (MYD)","coast",["malindi airport","myd"]],["lamu","Lamu / Manda Airport","coast",["lamu","manda airport","lau"]],
["naivasha","Naivasha","rift",["naivasha"]],["nakuru","Nakuru","rift",["nakuru"]],["lake-nakuru","Lake Nakuru National Park","rift",["lake nakuru"]],["narok","Narok","rift",["narok"]],["maasai-mara","Maasai Mara","rift",["maasai mara","masai mara","mara"]],["sekenani","Sekenani Gate / Maasai Mara","rift",["sekenani","sekenani gate"]],["talek","Talek / Maasai Mara","rift",["talek"]],["lake-baringo","Lake Baringo","rift",["lake baringo"]],
["nanyuki","Nanyuki","central",["nanyuki"]],["mount-kenya","Mount Kenya / Naro Moru","central",["mount kenya","naro moru"]],["nyeri","Nyeri","central",["nyeri"]],["aberdares","Aberdare National Park","central",["aberdares","aberdare"]],["meru","Meru","central",["meru"]],["meru-national-park","Meru National Park","central",["meru national park"]],
["samburu","Samburu National Reserve","north",["samburu"]],["isiolo","Isiolo","north",["isiolo"]],["isiolo-airport","Isiolo Airport","north",["isiolo airport"]],["marsabit","Marsabit","north",["marsabit"]],
["kisumu-airport","Kisumu International Airport (KIS)","west",["kis","kisumu airport"]],["kisumu","Kisumu","west",["kisumu"]],["eldoret-airport","Eldoret International Airport (EDL)","west",["edl","eldoret airport"]],["eldoret","Eldoret","west",["eldoret"]],["kakamega","Kakamega","west",["kakamega"]],["kitale","Kitale","west",["kitale"]]
].map(([slug,name,region,aliases])=>({slug:slug as string,name:name as string,region:region as KenyaZone["region"],aliases:aliases as string[]}));
export function keZone(slug:string){return kenyaZones.find(z=>z.slug===slug)}
export function resolveKenyaZone(input:string){const q=input.trim().toLowerCase();return kenyaZones.find(z=>z.name.toLowerCase()===q||z.aliases.some(a=>q===a||q.includes(a)))}
export function keCanonical(a:string,b:string):[string,string]{const ai=kenyaZones.findIndex(z=>z.slug===a),bi=kenyaZones.findIndex(z=>z.slug===b);return ai<=bi?[a,b]:[b,a]}
export function keRouteSlug(a:string,b:string){const[x,y]=keCanonical(a,b);return `${x}-to-${y}`}
export function kenyaPairs(){return kenyaZones.flatMap((a,i)=>kenyaZones.slice(i+1).map(b=>[a,b] as const))}
export const kenyaSeoPairs=new Set(["jkia-to-nairobi-cbd","jkia-to-westlands","jkia-to-karen","jkia-to-gigiri","jkia-to-upper-hill","jkia-to-wilson","jkia-to-nairobi-national-park","jkia-to-naivasha","jkia-to-nakuru","jkia-to-narok","jkia-to-maasai-mara","jkia-to-amboseli","jkia-to-namanga","wilson-to-maasai-mara","nairobi-cbd-to-naivasha","nairobi-cbd-to-nakuru","nairobi-cbd-to-maasai-mara","nairobi-cbd-to-amboseli","nairobi-cbd-to-namanga","mombasa-airport-to-mombasa","mombasa-airport-to-nyali","mombasa-airport-to-bamburi","mombasa-airport-to-diani","mombasa-to-diani","mombasa-to-watamu","mombasa-to-malindi","voi-to-tsavo-east","voi-to-taita-hills","mombasa-to-tsavo-east","mombasa-to-tsavo-west","nanyuki-to-samburu","nairobi-cbd-to-nanyuki","nairobi-cbd-to-samburu","kisumu-airport-to-kisumu","eldoret-airport-to-eldoret"]);
export function isKenyaSeoPair(a:string,b:string){return kenyaSeoPairs.has(keRouteSlug(a,b))}
export const kenyaHubSlugs=["jkia","nairobi-cbd","westlands","wilson","amboseli","voi","mombasa-airport","mombasa","diani","watamu","malindi","naivasha","nakuru","maasai-mara","nanyuki","samburu","kisumu-airport","eldoret-airport"] as const;