export type TanzaniaZone={slug:string;name:string;region:"north"|"coast"|"south"|"west";aliases:string[]};
export const tanzaniaZones:TanzaniaZone[]=[
["jro","Kilimanjaro International Airport (JRO)","north",["jro","kilimanjaro international airport","kia"]],["arusha","Arusha","north",["arusha city","arusha"]],["ark","Arusha Airport (ARK)","north",["ark","arusha airport"]],["moshi","Moshi","north",["moshi"]],["marangu","Marangu","north",["marangu"]],["machame","Machame","north",["machame"]],["materuni","Materuni","north",["materuni"]],["arusha-national-park","Arusha National Park","north",["arusha national park"]],["mkomazi","Mkomazi National Park","north",["mkomazi"]],["tarangire","Tarangire National Park","north",["tarangire"]],["mto-wa-mbu","Mto wa Mbu","north",["mto wa mbu"]],["lake-manyara","Lake Manyara National Park","north",["lake manyara","manyara"]],["karatu","Karatu","north",["karatu"]],["ngorongoro","Ngorongoro Conservation Area","north",["ngorongoro"]],["lake-eyasi","Lake Eyasi","north",["lake eyasi"]],["lake-natron","Lake Natron","north",["lake natron"]],["serengeti-naabi","Serengeti — Naabi Hill Gate","north",["naabi hill","naabi"]],["seronera","Seronera / Central Serengeti","north",["seronera","central serengeti"]],["kogatende","Kogatende / Northern Serengeti","north",["kogatende","northern serengeti"]],["ndutu","Ndutu","north",["ndutu"]],["mwanza","Mwanza","north",["mwanza"]],["jnia","Julius Nyerere International Airport (DAR)","coast",["jnia","dar airport","julius nyerere international airport"]],["dar-city","Dar es Salaam","coast",["dar es salaam","dar city"]],["dar-ferry","Dar es Salaam Ferry Terminal","coast",["zanzibar ferry","dar ferry","ferry terminal"]],["bagamoyo","Bagamoyo","coast",["bagamoyo"]],["saadani","Saadani National Park","coast",["saadani"]],["morogoro","Morogoro","south",["morogoro"]],["mikumi","Mikumi National Park","south",["mikumi"]],["udzungwa","Udzungwa Mountains National Park","south",["udzungwa"]],["iringa","Iringa","south",["iringa"]],["ruaha","Ruaha National Park","south",["ruaha"]],["nyerere","Nyerere National Park","south",["nyerere","selous"]],["mbeya","Mbeya","south",["mbeya"]],["kitulo","Kitulo National Park","south",["kitulo"]],["kigoma","Kigoma","west",["kigoma"]],["gombe","Gombe National Park gateway","west",["gombe"]],["mahale","Mahale Mountains gateway","west",["mahale"]],["katavi","Katavi National Park","west",["katavi"]],["rubondo","Rubondo Island gateway","west",["rubondo"]],["bukoba","Bukoba","west",["bukoba"]]
].map(([slug,name,region,aliases])=>({slug:slug as string,name:name as string,region:region as TanzaniaZone["region"],aliases:aliases as string[]}));
export function tzZone(slug:string){return tanzaniaZones.find(z=>z.slug===slug)}
export function resolveTanzaniaZone(input:string){const q=input.trim().toLowerCase();return tanzaniaZones.find(z=>z.name.toLowerCase()===q||z.aliases.some(a=>q.includes(a)))}
export function tzCanonical(a:string,b:string):[string,string]{const ai=tanzaniaZones.findIndex(z=>z.slug===a),bi=tanzaniaZones.findIndex(z=>z.slug===b);return ai<=bi?[a,b]:[b,a]}
export function tzRouteSlug(a:string,b:string){const[x,y]=tzCanonical(a,b);return `${x}-to-${y}`}
export function tanzaniaPairs(){return tanzaniaZones.flatMap((a,i)=>tanzaniaZones.slice(i+1).map(b=>[a,b] as const))}
export const tanzaniaSeoPairs=new Set(["jro-to-arusha","jro-to-moshi","jro-to-tarangire","jro-to-karatu","jro-to-ngorongoro","jro-to-seronera","arusha-to-tarangire","arusha-to-lake-manyara","arusha-to-karatu","arusha-to-ngorongoro","arusha-to-seronera","arusha-to-kogatende","arusha-to-moshi","tarangire-to-karatu","tarangire-to-ngorongoro","karatu-to-ngorongoro","karatu-to-seronera","ngorongoro-to-seronera","seronera-to-kogatende","jnia-to-dar-city","jnia-to-dar-ferry","dar-city-to-bagamoyo","dar-city-to-mikumi","dar-city-to-nyerere","morogoro-to-mikumi","iringa-to-ruaha","kigoma-to-gombe","kigoma-to-mahale"]);
export function isTanzaniaSeoPair(a:string,b:string){return tanzaniaSeoPairs.has(tzRouteSlug(a,b))}
export const tanzaniaHubSlugs=["jro","arusha","moshi","tarangire","karatu","ngorongoro","seronera","jnia","dar-city","mikumi","nyerere","iringa","ruaha","kigoma"] as const;