export type ZambiaZone={slug:string;name:string;region:"lusaka"|"livingstone"|"luangwa"|"zambezi"|"kafue"|"copperbelt"|"north"|"west";aliases:string[]};export const zambiaZones:ZambiaZone[]=[
["lun","Kenneth Kaunda International Airport (LUN)","lusaka",["lun","kenneth kaunda international airport","lusaka airport","kkia"]],["lusaka","Lusaka","lusaka",["lusaka","lusaka cbd"]],["longacres","Longacres","lusaka",["longacres"]],["kabulonga","Kabulonga","lusaka",["kabulonga"]],["roma","Roma / EastPark","lusaka",["roma","eastpark","east park"]],["lusaka-national-park","Lusaka National Park","lusaka",["lusaka national park"]],["chirundu","Chirundu Border","lusaka",["chirundu","chirundu border"]],
["lvi","Harry Mwaanga Nkumbula International Airport (LVI)","livingstone",["lvi","livingstone airport","harry mwaanga nkumbula international airport"]],["livingstone","Livingstone","livingstone",["livingstone"]],["victoria-falls","Victoria Falls / Mosi-oa-Tunya","livingstone",["victoria falls","mosi oa tunya","mosi-oa-tunya"]],["kazungula","Kazungula Border","livingstone",["kazungula","kazungula border"]],["sesheke","Sesheke","livingstone",["sesheke"]],
["mfu","Mfuwe International Airport (MFU)","luangwa",["mfu","mfuwe airport","mfuwe international airport"]],["mfuwe","Mfuwe","luangwa",["mfuwe"]],["south-luangwa","South Luangwa National Park","luangwa",["south luangwa","south luangwa national park"]],["chipata","Chipata","luangwa",["chipata"]],["petauke","Petauke","luangwa",["petauke"]],
["lower-zambezi","Lower Zambezi National Park","zambezi",["lower zambezi","lower zambezi national park"]],["jeki","Jeki Airstrip / Lower Zambezi","zambezi",["jeki","jeki airstrip"]],["royal","Royal Airstrip / Lower Zambezi","zambezi",["royal airstrip","royal"]],["siavonga","Siavonga","zambezi",["siavonga"]],["kariba","Kariba / Lake Kariba","zambezi",["kariba","lake kariba"]],
["kafue-national-park","Kafue National Park","kafue",["kafue national park"]],["chingola-kafue","Kafue town","kafue",["kafue town"]],["lochinvar","Lochinvar National Park","kafue",["lochinvar"]],["blue-lagoon","Blue Lagoon National Park","kafue",["blue lagoon national park"]],
["nla","Simon Mwansa Kapwepwe International Airport (NLA)","copperbelt",["nla","ndola airport","simon mwansa kapwepwe international airport"]],["ndola","Ndola","copperbelt",["ndola"]],["kitwe","Kitwe","copperbelt",["kitwe"]],["chingola","Chingola","copperbelt",["chingola"]],["solwezi","Solwezi","copperbelt",["solwezi"]],["solwezi-airport","Solwezi Airport","copperbelt",["solwezi airport"]],
["kasama","Kasama","north",["kasama"]],["kasama-airport","Kasama Airport","north",["kasama airport"]],["mansa","Mansa","north",["mansa"]],["mansa-airport","Mansa Airport","north",["mansa airport"]],["samfya","Samfya","north",["samfya"]],["bangweulu","Bangweulu Wetlands","north",["bangweulu","bangweulu wetlands"]],
["mongu","Mongu","west",["mongu"]],["liuawa","Liuwa Plain National Park","west",["liuwa plain","liuwa plain national park"]]
].map(([slug,name,region,aliases])=>({slug:slug as string,name:name as string,region:region as ZambiaZone["region"],aliases:aliases as string[]}));export function zmZone(slug:string){return zambiaZones.find(z=>z.slug===slug)}export function resolveZambiaZone(input:string){const q=input.trim().toLowerCase();return zambiaZones.find(z=>z.name.toLowerCase()===q||z.aliases.some(a=>q===a||q.includes(a)))}export function zmCanonical(a:string,b:string):[string,string]{const ai=zambiaZones.findIndex(z=>z.slug===a),bi=zambiaZones.findIndex(z=>z.slug===b);return ai<=bi?[a,b]:[b,a]}export function zmRouteSlug(a:string,b:string){const[x,y]=zmCanonical(a,b);return `${x}-to-${y}`}export function zambiaPairs(){return zambiaZones.flatMap((a,i)=>zambiaZones.slice(i+1).map(b=>[a,b] as const))}export const zambiaSeoPairs=new Set(["lun-to-lusaka","lun-to-longacres","lun-to-kabulonga","lun-to-roma","lun-to-lusaka-national-park","lun-to-livingstone","lun-to-siavonga","lun-to-lower-zambezi","lusaka-to-livingstone","lusaka-to-siavonga","lusaka-to-chirundu","lusaka-to-kafue-national-park","lvi-to-livingstone","lvi-to-victoria-falls","lvi-to-kazungula","livingstone-to-victoria-falls","livingstone-to-kazungula","mfu-to-mfuwe","mfu-to-south-luangwa","mfuwe-to-south-luangwa","chipata-to-mfuwe","chipata-to-south-luangwa","lun-to-chipata","nla-to-ndola","nla-to-kitwe","ndola-to-kitwe","ndola-to-chingola","ndola-to-solwezi","solwezi-airport-to-solwezi","lusaka-to-ndola","lusaka-to-kitwe","lusaka-to-mfuwe","jeki-to-lower-zambezi","royal-to-lower-zambezi","kasama-airport-to-kasama","mansa-airport-to-mansa"]);export function isZambiaSeoPair(a:string,b:string){return zambiaSeoPairs.has(zmRouteSlug(a,b))}export const zambiaHubSlugs=["lun","lusaka","lvi","livingstone","victoria-falls","mfu","mfuwe","south-luangwa","lower-zambezi","siavonga","kafue-national-park","nla","ndola","kitwe","solwezi","kasama","mansa","samfya"] as const;